// Copyright 2021 Betamark Pty Ltd. All rights reserved.
// Author: Shlomi Nissan (shlomi@betamark.com)

#ifndef TREX_RUNNER_GLOBALS_H
#define TREX_RUNNER_GLOBALS_H

#define ACCELERATION 0.001
#define ACHIEVEMENT_DISTANCE 100
#define CLEAR_TIME 3000
#define CLOUDS_FREQUENCY 5
#define CLOUD_GAP_MAX 400
#define CLOUD_GAP_MIN 100
#define CLOUD_SKY_LEVEL_MAX 71
#define CLOUD_SKY_LEVEL_MIN 30
#define DEBUG_DRAW 0
#define DISTANCE_COEFFICIENT 0.025
#define DISTANCE_FLASH_DURATION 1000 / 4
#define DISTANCE_FLASH_ITERATIONS 3
#define DROP_VELOCITY -5
#define FPS 60
#define GAME_OVER_CLEAR_TIME 400
#define GRAVITY 0.6
#define GROUND_OFFSET 10
#define INITIAL_JUMP_VELOCITY -10
#define MAX_CLOUD_LENGTH 6
#define MAX_DISTANCE_UNITS 5
#define MAX_JUMP_HEIGHT 30
#define MAX_OBSTACLE_LENGTH 2
#define MAX_SPEED 13
#define MIN_JUMP_HEIGHT 35
#define OBSTACLE_MAX_GAP_COEFFICIENT 1.5
#define OBSTACLE_MIN_GAP_COEFFICIENT 0.6
#define SPEED 6
#define SPEED_DROP_COEFFICIENT 3
#define WINDOW_TITLE "T-Rex Runner"
#define WINDOW_WIDTH 600
#define WINDOW_HEIGHT 150

#endif  // TREX_RUNNER_GLOBALS_H
